# -*- coding: utf-8 -*-
"""pet

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1tdTGkBAB-6NLg8i_ns4ej5Y9GxNH9Ypx
"""

class Pet:
    def __init__(self, name):
        self.name = name
        self.happy = 100
        self.hunger = 100
        self.health = 100

    def feed(self):
      self.hunger -= 20

    def walk(self):
      self.health += 10
      self.happy += 5

    def pet(self):
      self.happy += 10

    def cage(self):
      self.happy -= 10